jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: License Check
      run: mvn apache-rat:check "-Drat.consoleOutput"
    - continue-on-error: true
      name: Build with Maven
      run: mvn verify --show-version --errors --batch-mode --no-transfer-progress
        -Pdocs -Dgh_user=${{ github.actor }} -Dgh_token=${{ secrets.GITHUB_TOKEN }}
  build-all:
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: ${{ matrix.dist }}
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      if: matrix.os == 'ubuntu-latest' && matrix.jdk <= 17
      name: Build with Maven (Linux)
      run: mvn verify --show-version --errors --batch-mode --no-transfer-progress
        -Pdocs -Dgh_user=${{ github.actor }} -Dgh_token=${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: matrix.os != 'ubuntu-latest' || matrix.jdk > 17
      name: Build with Maven (non-Linux or JDK > 17)
      run: mvn verify --show-version --errors --batch-mode --no-transfer-progress
        -Pdocs -Pskip_jakarta_ee_tests
    - continue-on-error: true
      if: always()
      name: Archive test run logs
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        name: test-logs-${{ matrix.os }}-${{ matrix.jdk }}-${{ matrix.dist }}
        path: '**/target/failsafe-reports/*-output.txt

          **/target/**/logs/server.log

          '
    strategy:
      fail-fast: false
      matrix:
        dist:
        - temurin
        - adopt-openj9
        - zulu
        exclude:
        - dist: temurin
          jdk: 11
          os: ubuntu-latest
        - dist: temurin
          os: macOS-latest
        - dist: temurin
          jdk: 21
        - dist: adopt-openj9
          jdk: 21
        - dist: adopt-openj9
          jdk: 22
        jdk:
        - 11
        - 17
        - 21
        - 22
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
name: Maven CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions:
  contents: read
