jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Close Stale Issues
      uses: actions/stale@v9
      with:
        days-before-stale: 90
name: Maven CI
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
  issues: write
  pull-requests: write
